Fix CI Release Syntax (#38)
This PR fixes (hopefully) an error:

```
Error: .github/workflows/release_nightly.yml (Line: 43, Col: 19): A sequence was not expected
Error: The template is not valid. .github/workflows/release_nightly.yml (Line: 43, Col: 19): A sequence was not expected
```

I kind of expect the Releases to need some more work anyways, so also enabling manual triggering for the nightly release workflow.